services:

  db:
    image: mysql:lts
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${MYSQL_SCHEMA}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  mysql-data: